#!/usr/bin/env python

import sys
import pdfcrowd

args = []

if len(sys.argv) == 1 or sys.argv[1] == 'help':
    args.append('help')

args.append('pdf2html')

try:
    pdfcrowd.main(args + sys.argv[1:], converter_known = True)
except pdfcrowd.Error as why:
    sys.stderr.write('PDFCrowd Error: {}\n'.format(why))
    sys.exit(1)
